[0m21:30:00.701658 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277749BD460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027776D7A390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027776D7B530>]}


============================== 21:30:00.719282 | 05dfa71b-0685-40f4-ad22-1467a7208564 ==============================
[0m21:30:00.719282 [info ] [MainThread]: Running with dbt=1.8.9
[0m21:30:00.721292 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\megha\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init notebook_project', 'send_anonymous_usage_stats': 'True'}
[0m21:30:00.776844 [debug] [MainThread]: Starter project path: C:\Users\megha\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m21:30:00.814974 [info ] [MainThread]: 
Your new dbt project "notebook_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:30:00.814974 [info ] [MainThread]: Setting up your profile.
[0m21:30:56.423139 [debug] [MainThread]: Command `dbt init` succeeded at 21:30:56.423139 after 56.08 seconds
[0m21:30:56.423139 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027777BB6C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277777891F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027777C03B90>]}
[0m21:30:56.423139 [debug] [MainThread]: Flushing usage events
[0m21:36:25.976639 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000260D6784860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000260D84CB0B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000260D84CA900>]}


============================== 21:36:25.985953 | 942a493a-afe7-48ce-8d2b-39278ec3ae02 ==============================
[0m21:36:25.985953 [info ] [MainThread]: Running with dbt=1.8.9
[0m21:36:25.992397 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\megha\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt seed', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m21:36:25.992397 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\megha\Documents\ResearchWork\DBTProjects\JupyterNotebook\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:36:25.992397 [debug] [MainThread]: Command `dbt seed` failed at 21:36:25.992397 after 0.27 seconds
[0m21:36:25.992397 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000260D8FF5D60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000260D8E269F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000260D932E210>]}
[0m21:36:25.996101 [debug] [MainThread]: Flushing usage events
